### ISSUE TITLE
Lab 04 Step 2 

### ISSUE THREAD

**Issue by asukajames** [Watts-College/cpp-529-spr-2022#10]
Hello! 
I am confused with Step 2, Census API calls part. 
I have selected Washington DC for this project and as I searched the city in NBER, it came back as 
 "WASHINGTON, DC-MD-VA-WV"

In the lab instruction, Minneapolis - St. Paul, MN-WI, it spans two states. 
In my case, it spans four states (**DC**-MD-VA_WV)? Is DC counted as a state? 

However, as I run this chunk, I only see **three state fips**: 
```{r}
state.fips <- substr( these.fips, 1, 2 )
county.fips <- substr( these.fips, 3, 5 )

cbind( these.fips, state.fips, county.fips ) %>% pander()
``` 

![state fips](https://user-images.githubusercontent.com/88746310/161590505-362e9bd8-c0c5-47a6-b8e9-5cb2ad2cd9a3.JPG)

If it spans three states, I need three Census API Calls, correct? 

```{r}
msp.pop1 <-
get_acs( geography = "tract", variables = "B01003_001",
         state = "11", county = county.fips[state.fips=="11"], geometry = TRUE ) %>% 
         select( GEOID, estimate ) %>%
         rename( POP=estimate ) 
```

**Comment by ramacdo1** [comment]
Hi! I think you are misreading, you have four state fips codes: 11, 24, 51, and 54! DC fips state code is 11!

**Comment by JasonSills** [comment]
Hi, @asukajames, yes try running it with your logic (four times) and see what happens! Repeat the steps for MSP in the tutorial, but across the four fips codes and see what it returns! Working in data science is all about experimentation.

**Comment by asukajames** [comment]
Thank you @JasonSills and @ramacdo1 :-) !!
