### ISSUE TITLE
Gentrification Video Slides Missing?

### ISSUE THREAD

**Issue by droach7** [Watts-College/cpp-529-spr-2022#18]
@JasonSills 

I went to watch the video lecture on gentrification today and noticed that the hyperlinked lecture notes were actually the same visual narrative notes linked later on above the second video. So instead of having one copy of the gentrification lecture slides and one copy of the visual narrative slides there are two copies of the visual narrative slides.  Could you please update the first link to include the gentrification slides or post them somewhere else?

**Comment by JasonSills** [comment]
Adding in @jbpratt1 to double check the links mentioned above.

**Comment by JasonSills** [comment]
@droach7,

I have sent out an announcement with the slides on gentrification. Please find them in that link, it is possible we will not be able to update the website.

**Comment by droach7** [comment]
@JasonSills Great, thank you!
