### ISSUE TITLE
Github Raw Geojson URL Issues? 

### ISSUE THREAD

**Issue by droach7** [Watts-College/cpp-529-spr-2022#26]
@JasonSills 

Hi, I was able to save and upload my cartogram to GitHub, and was able to get the raw URL (I hade to click "download" instead of "raw" to be directed to the raw code URL) and load it into my final dashboard. I fixed the other parts of the dashboard code that would prevent the document from running. 

However, I noticed a strange thing. I would get everything working, and then about 10 minutes later, with no change to the code (only added comments)  if I tried to rerun the document it would give an error indicating a false URL. I then reopened GitHub, copied  the raw URL again and pasted it into R. I realized that the raw URL changed? And keeps changing... like every 10 minutes. For obvious reasons, this makes it quite difficult to work on my dashboard. Could you please tell me what I need to do to prevent this from happening?

**Comment by JasonSills** [comment]
@droach7 ,

Can you provide an example of the URL you are using?

**Comment by droach7** [comment]
> Can you provide an example of the URL you are using?
 
Sure thing! Here is the most recent raw URL it spits out at me: https://raw.githubusercontent.com/droach7/DRoach-Sacramento/main/sac_dorling.geojson?token=GHSAT0AAAAAABTZYKCBDAHS5PTDMVU6265QYTEQC5A

**Comment by JasonSills** [comment]
@droach7 
The URL is generating a token on at the end of the URL (token=GHSAT0AAAAAABTZYKCBDAHS5PTDMVU6265QYTEQC5A in the URL. This is what is changing. Check your repository to make sure it is public, rather than private.  You can check this next to the name of the repository:

<img width="177" alt="image" src="https://user-images.githubusercontent.com/54817638/164948807-8ddc15f2-8133-4403-a0fa-62c430bf9021.png">

**Comment by droach7** [comment]
> Check your repository to make sure it is public, rather than private. You can check this next to the name of the repository

Of course my personal data protecting ways have led to my difficulties. Haha!

Thanks for your help Jason!
