### ISSUE TITLE
Final Project Deliverables

### ISSUE THREAD

**Issue by droach7** [Watts-College/cpp-529-spr-2022#34]
@JasonSills 

In the final project instructions it says to submit the RMD file, HTML file, and the URL of your published dashboard. It is my understanding that when running a shiny.app in an RMD file that it can't be knitted to HTML. Is this correct?

If so, are our only submittals the RMD file and published URL?

**Comment by JasonSills** [comment]
@droach7, 

You can run new markdown file. Create a new markdown file and use the YAML:

title: "Models of Neighborhood Change in Your City"

output: html_document

**Comment by droach7** [comment]
Great, thanks for clarifying!
