### ISSUE TITLE
Final project submission

### ISSUE THREAD

**Issue by dholford** [Watts-College/cpp-529-spr-2022#35]
Hello @JasonSills,

I'm a little confused on what all we are supposed to be submitting. The final project instructions say to submit the following:

1. Create an RMD file with the all of the datasets described below. In this file you will re-create your dorling cartogram, add your clusters, and add all of the census data needed for your models. This will allow you to load a single geojson map file in your dashboard, and it will contain all of the information you need for all of the tabs.

2. Use the template above to create a dashboard that makes all of the data on your city acccessible. Submit the .rmd file, the .html files for your dashboard.

3. Upload a your completed dashboard to shiny.io so that you can share your work via a URL. Include the link to your dashboard in the comments of your project submission, and share your work with classmates via Yellowdig.

I'm a little confused on what .html file we should have? And should we be submitting our dorling cartogram file separately?

Thanks,
Dylan

**Comment by JasonSills** [comment]
I don't need the dorling cartogram file, just the rmd used to create the file. The html file would be similar to what you run with other markdowns and submit with your labs. Create a new rmarkdown, put your dashboard code in it, and use the yaml:

title: "Models of Neighborhood Change in Your City"
output: html_document

**Comment by dholford** [comment]
@JasonSills 

Awesome, thanks for the quick response!
