### ISSUE TITLE
Model Variable Names

### ISSUE THREAD

**Issue by AmyTrumpower** [Watts-College/cpp-529-spr-2022#38]
@JasonSills 
@u12345 

Now that the due date for the dashboard has passed would someone please tell me how to change the variables from values to names on the graphs and the model? I don’t think I saw that anyone had the names in the .tabset except for the correlation plot. I might have missed it. 

I think I spent 2 full days just on that madness. I could not find anything for reactive data. I’m sure it’s going to be a facepalm but for now I’m going to have to use my _Phone A Friend_

Thanks!
Amy

**Comment by JasonSills** [comment]
@AmyTrumpower,

I will post this after the grading deadline of May 9.
