### ISSUE TITLE
Lab 3 Running The Chunks

### ISSUE THREAD

**Issue by AmyTrumpower** [Watts-College/cpp-529-spr-2022#9]
Hi:
I understand the week 3 assignment is the word doc with the questions and the labels for the 8 clusters, but I thought we were also supposed to run the chunks in the RMD file in prep for next week. When I tried to run the file I had issues on the Load Phoenix Shapefile chunk starting on line 62. 

```{r}
# dorling cartogram of Phoenix Census Tracts
github.url <- "https://raw.githubusercontent.com/DS4PS/cpp-529-master/master/data/phx_dorling.geojson"
phx <- geojson_read( x=github.url,  what="sp" )
plot( phx )
```

Error in curl::curl_fetch_disk(x$url$url, x$disk, handle = x$url$handle) : 
  schannel: failed to receive handshake, SSL/TLS connection failed

There may have been something I was supposed to do?
Thanks,
Amy

**Comment by u12345** [comment]
@AmyTrumpower ,

Have you installed these packages?
install.packages("geojsonio")
install.packages("devtools")
devtools::install_github("ropensci/geojsonio")
library("geojsonio")
library( sp )          # work with shapefiles
library( sf )          # work with shapefiles - simple features format
library( mclust )      # cluster analysis 
library( tmap )        # theme maps
library( ggplot2 )     # graphing 
library( ggthemes )
library( dplyr )
library( pander )

Try to do name(phx) to see if you are getting any data before plot(phx).

Ujitha

**Comment by AmyTrumpower** [comment]
That seemed to work b/c I am seeing the cluster maps now. Thank you for your help!.
Amy

**Comment by u12345** [comment]
resolved.
